import = [
    "~/.config/alacritty/themes/themes/papercolor_dark.toml"
]

[font]
size = 8.5

[font.bold]
family = "Inconsolata Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Inconsolata Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Inconsolata Nerd Font"
style = "Italic"

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

[keyboard]
# open new terminal in current directory
bindings = [
   { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" }
]

[window]
padding = {x = 2, y = 0}

[selection]
save_to_clipboard = true

